"""add original_price and videos to product

Revision ID: 366026b0057f
Revises: 8844cd2cb228
Create Date: 2026-07-22 17:04:27.472957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366026b0057f'
down_revision: Union[str, None] = '8844cd2cb228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('videos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'videos')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
