"""add_staff_fields

Revision ID: 69fe08305d8c
Revises: 366026b0057f
Create Date: 2026-08-01 09:52:34.313934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fe08305d8c'
down_revision: Union[str, None] = '366026b0057f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profiles', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('staff_profiles', sa.Column('id_proof_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('staff_profiles', 'id_proof_url')
    op.drop_column('staff_profiles', 'address')
    # ### end Alembic commands ###
