/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminPosRouteImport } from './routes/admin.pos'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as BuyIdRouteImport } from './routes/buy.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as StaffLeaveRouteImport } from './routes/staff.leave'
import { Route as StaffOrdersRouteImport } from './routes/staff.orders'
import { Route as StaffPosRouteImport } from './routes/staff.pos'
import { Route as StaffProductsRouteImport } from './routes/staff.products'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as AdminInventoryAddRouteImport } from './routes/admin.inventory_.add'
import { Route as StaffProductsAddRouteImport } from './routes/staff.products_.add'
import { Route as AdminInventoryIdEditRouteImport } from './routes/admin.inventory_.$id.edit'
import { Route as StaffProductsIdEditRouteImport } from './routes/staff.products_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/admin/pos',
  path: '/admin/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIdRoute = BuyIdRouteImport.update({
  id: '/buy/$id',
  path: '/buy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff/attendance',
  path: '/staff/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLeaveRoute = StaffLeaveRouteImport.update({
  id: '/staff/leave',
  path: '/staff/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/staff/orders',
  path: '/staff/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPosRoute = StaffPosRouteImport.update({
  id: '/staff/pos',
  path: '/staff/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProductsRoute = StaffProductsRouteImport.update({
  id: '/staff/products',
  path: '/staff/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/staff/reports',
  path: '/staff/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryAddRoute = AdminInventoryAddRouteImport.update({
  id: '/admin/inventory_/add',
  path: '/admin/inventory/add',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProductsAddRoute = StaffProductsAddRouteImport.update({
  id: '/staff/products_/add',
  path: '/staff/products/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIdEditRoute = AdminInventoryIdEditRouteImport.update({
  id: '/admin/inventory_/$id/edit',
  path: '/admin/inventory/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProductsIdEditRoute = StaffProductsIdEditRouteImport.update({
  id: '/staff/products_/$id/edit',
  path: '/staff/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/buy/$id': typeof BuyIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/inventory/add': typeof AdminInventoryAddRoute
  '/staff/products/add': typeof StaffProductsAddRoute
  '/admin/inventory/$id/edit': typeof AdminInventoryIdEditRoute
  '/staff/products/$id/edit': typeof StaffProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/buy/$id': typeof BuyIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin': typeof AdminIndexRoute
  '/buy': typeof BuyIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/inventory/add': typeof AdminInventoryAddRoute
  '/staff/products/add': typeof StaffProductsAddRoute
  '/admin/inventory/$id/edit': typeof AdminInventoryIdEditRoute
  '/staff/products/$id/edit': typeof StaffProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/wishlist': typeof WishlistRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/buy/$id': typeof BuyIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leave': typeof StaffLeaveRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/pos': typeof StaffPosRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/reports': typeof StaffReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/inventory_/add': typeof AdminInventoryAddRoute
  '/staff/products_/add': typeof StaffProductsAddRoute
  '/admin/inventory_/$id/edit': typeof AdminInventoryIdEditRoute
  '/staff/products_/$id/edit': typeof StaffProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/sell'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin/staff'
    | '/buy/$id'
    | '/orders/$id'
    | '/staff/attendance'
    | '/staff/leave'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/reports'
    | '/admin/'
    | '/buy/'
    | '/staff/'
    | '/admin/inventory/add'
    | '/staff/products/add'
    | '/admin/inventory/$id/edit'
    | '/staff/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/sell'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin/staff'
    | '/buy/$id'
    | '/orders/$id'
    | '/staff/attendance'
    | '/staff/leave'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/reports'
    | '/admin'
    | '/buy'
    | '/staff'
    | '/admin/inventory/add'
    | '/staff/products/add'
    | '/admin/inventory/$id/edit'
    | '/staff/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/sell'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/wishlist'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin/staff'
    | '/buy/$id'
    | '/orders/$id'
    | '/staff/attendance'
    | '/staff/leave'
    | '/staff/orders'
    | '/staff/pos'
    | '/staff/products'
    | '/staff/reports'
    | '/admin/'
    | '/buy/'
    | '/staff/'
    | '/admin/inventory_/add'
    | '/staff/products_/add'
    | '/admin/inventory_/$id/edit'
    | '/staff/products_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WishlistRoute: typeof WishlistRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  BuyIdRoute: typeof BuyIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffLeaveRoute: typeof StaffLeaveRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffPosRoute: typeof StaffPosRoute
  StaffProductsRoute: typeof StaffProductsRoute
  StaffReportsRoute: typeof StaffReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BuyIndexRoute: typeof BuyIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  AdminInventoryAddRoute: typeof AdminInventoryAddRoute
  StaffProductsAddRoute: typeof StaffProductsAddRoute
  AdminInventoryIdEditRoute: typeof AdminInventoryIdEditRoute
  StaffProductsIdEditRoute: typeof StaffProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/admin/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$id': {
      id: '/buy/$id'
      path: '/buy/$id'
      fullPath: '/buy/$id'
      preLoaderRoute: typeof BuyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/leave': {
      id: '/staff/leave'
      path: '/staff/leave'
      fullPath: '/staff/leave'
      preLoaderRoute: typeof StaffLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/staff/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pos': {
      id: '/staff/pos'
      path: '/staff/pos'
      fullPath: '/staff/pos'
      preLoaderRoute: typeof StaffPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/products': {
      id: '/staff/products'
      path: '/staff/products'
      fullPath: '/staff/products'
      preLoaderRoute: typeof StaffProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/staff/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory_/add': {
      id: '/admin/inventory_/add'
      path: '/admin/inventory/add'
      fullPath: '/admin/inventory/add'
      preLoaderRoute: typeof AdminInventoryAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/products_/add': {
      id: '/staff/products_/add'
      path: '/staff/products/add'
      fullPath: '/staff/products/add'
      preLoaderRoute: typeof StaffProductsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory_/$id/edit': {
      id: '/admin/inventory_/$id/edit'
      path: '/admin/inventory/$id/edit'
      fullPath: '/admin/inventory/$id/edit'
      preLoaderRoute: typeof AdminInventoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/products_/$id/edit': {
      id: '/staff/products_/$id/edit'
      path: '/staff/products/$id/edit'
      fullPath: '/staff/products/$id/edit'
      preLoaderRoute: typeof StaffProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WishlistRoute: WishlistRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminPosRoute: AdminPosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  BuyIdRoute: BuyIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffLeaveRoute: StaffLeaveRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffPosRoute: StaffPosRoute,
  StaffProductsRoute: StaffProductsRoute,
  StaffReportsRoute: StaffReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
  BuyIndexRoute: BuyIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  AdminInventoryAddRoute: AdminInventoryAddRoute,
  StaffProductsAddRoute: StaffProductsAddRoute,
  AdminInventoryIdEditRoute: AdminInventoryIdEditRoute,
  StaffProductsIdEditRoute: StaffProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

